// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA954B_U14oji7vwWqRDY3d9fNSXVBNZfQ',
    appId: '1:826028938596:web:a1d8807bce84b178a39671',
    messagingSenderId: '826028938596',
    projectId: 'alu-connect-b0090',
    authDomain: 'alu-connect-b0090.firebaseapp.com',
    storageBucket: 'alu-connect-b0090.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDb9wIP2MjHIys5TSEs0w5mxW2FJ880yY',
    appId: '1:826028938596:android:29ecf83265fd8fd0a39671',
    messagingSenderId: '826028938596',
    projectId: 'alu-connect-b0090',
    storageBucket: 'alu-connect-b0090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOJhXcg43MHAP8_tspc1dUO7pXe2X1XA',
    appId: '1:826028938596:ios:0d626fafbd44d76ba39671',
    messagingSenderId: '826028938596',
    projectId: 'alu-connect-b0090',
    storageBucket: 'alu-connect-b0090.firebasestorage.app',
    iosBundleId: 'com.example.formativeAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOJhXcg43MHAP8_tspc1dUO7pXe2X1XA',
    appId: '1:826028938596:ios:0d626fafbd44d76ba39671',
    messagingSenderId: '826028938596',
    projectId: 'alu-connect-b0090',
    storageBucket: 'alu-connect-b0090.firebasestorage.app',
    iosBundleId: 'com.example.formativeAssignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA954B_U14oji7vwWqRDY3d9fNSXVBNZfQ',
    appId: '1:826028938596:web:892cd5a786ac4d44a39671',
    messagingSenderId: '826028938596',
    projectId: 'alu-connect-b0090',
    authDomain: 'alu-connect-b0090.firebaseapp.com',
    storageBucket: 'alu-connect-b0090.firebasestorage.app',
  );
}
